project_name: demo-rest
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
dockers:
  - image_templates:
      - "ghcr.io/cerbos/demo-rest:latest"
      - "ghcr.io/cerbos/demo-rest:{{ .Version }}"
checksum:
  disable: true
changelog:
  skip: true
