---
name: 'cerbos'
description: 'Cerbos compile and test'
inputs:
  policyDir:
    description: 'Policy directory'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/cerbos/cerbos:0.6.0'
  args:
    - 'compile'
    - ${{ inputs.policyDir }}
